
// This file has been generated by the GUI designer. Do not modify.

public partial class FullscreenPreviewWindow {
    private Gtk.Table table2;
    private Gtk.HBox hbox2;
    private Gtk.Image image53;
    private Gtk.Label lblName;
    private Gtk.Fixed fixed2;
    private Gtk.Button btnSettings;
    private Gtk.Button btnPrevious;
    private Gtk.Button btnNext;
    private Gtk.Button btnExit;
    private Gtk.DrawingArea ssPreviewArea;

    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget FullscreenPreviewWindow
        this.Name = "FullscreenPreviewWindow";
        this.Title = Mono.Unix.Catalog.GetString("FullscreenPreviewWindow");
        this.Icon = Gdk.Pixbuf.LoadFromResource("screensaversettings.icon.png");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child FullscreenPreviewWindow.Gtk.Container+ContainerChild
        this.table2 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
        this.table2.Name = "table2";
        this.table2.RowSpacing = ((uint)(6));
        this.table2.ColumnSpacing = ((uint)(6));
        // Container child table2.Gtk.Table+TableChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.image53 = new Gtk.Image();
        this.image53.Name = "image53";
        this.image53.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-info", Gtk.IconSize.Menu);
        this.hbox2.Add(this.image53);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox2[this.image53]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        w1.Padding = ((uint)(4));
        // Container child hbox2.Gtk.Box+BoxChild
        this.lblName = new Gtk.Label();
        this.lblName.Name = "lblName";
        this.lblName.LabelProp = Mono.Unix.Catalog.GetString("<b>Screensaver Name</b>");
        this.lblName.UseMarkup = true;
        this.hbox2.Add(this.lblName);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.lblName]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.fixed2 = new Gtk.Fixed();
        this.fixed2.Name = "fixed2";
        this.fixed2.HasWindow = false;
        this.hbox2.Add(this.fixed2);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.fixed2]));
        w3.Position = 2;
        // Container child hbox2.Gtk.Box+BoxChild
        this.btnSettings = new Gtk.Button();
        this.btnSettings.CanFocus = true;
        this.btnSettings.Name = "btnSettings";
        this.btnSettings.UseUnderline = true;
        // Container child btnSettings.Gtk.Container+ContainerChild
        Gtk.Alignment w4 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w5 = new Gtk.HBox();
        w5.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w6 = new Gtk.Image();
        w6.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-properties", Gtk.IconSize.Menu);
        w5.Add(w6);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w8 = new Gtk.Label();
        w8.LabelProp = Mono.Unix.Catalog.GetString("_Options");
        w8.UseUnderline = true;
        w5.Add(w8);
        w4.Add(w5);
        this.btnSettings.Add(w4);
        this.hbox2.Add(this.btnSettings);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox2[this.btnSettings]));
        w12.Position = 3;
        w12.Expand = false;
        w12.Fill = false;
        w12.Padding = ((uint)(4));
        // Container child hbox2.Gtk.Box+BoxChild
        this.btnPrevious = new Gtk.Button();
        this.btnPrevious.CanFocus = true;
        this.btnPrevious.Name = "btnPrevious";
        this.btnPrevious.UseUnderline = true;
        // Container child btnPrevious.Gtk.Container+ContainerChild
        Gtk.Alignment w13 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w14 = new Gtk.HBox();
        w14.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w15 = new Gtk.Image();
        w15.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_left", Gtk.IconSize.Menu);
        w14.Add(w15);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w17 = new Gtk.Label();
        w14.Add(w17);
        w13.Add(w14);
        this.btnPrevious.Add(w13);
        this.hbox2.Add(this.btnPrevious);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox2[this.btnPrevious]));
        w21.Position = 4;
        w21.Expand = false;
        w21.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.btnNext = new Gtk.Button();
        this.btnNext.CanFocus = true;
        this.btnNext.Name = "btnNext";
        this.btnNext.UseUnderline = true;
        // Container child btnNext.Gtk.Container+ContainerChild
        Gtk.Alignment w22 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w23 = new Gtk.HBox();
        w23.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w24 = new Gtk.Image();
        w24.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_right", Gtk.IconSize.Menu);
        w23.Add(w24);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w26 = new Gtk.Label();
        w23.Add(w26);
        w22.Add(w23);
        this.btnNext.Add(w22);
        this.hbox2.Add(this.btnNext);
        Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.hbox2[this.btnNext]));
        w30.Position = 5;
        w30.Expand = false;
        w30.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.btnExit = new Gtk.Button();
        this.btnExit.CanFocus = true;
        this.btnExit.Name = "btnExit";
        this.btnExit.UseUnderline = true;
        // Container child btnExit.Gtk.Container+ContainerChild
        Gtk.Alignment w31 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w32 = new Gtk.HBox();
        w32.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w33 = new Gtk.Image();
        w33.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-quit", Gtk.IconSize.Menu);
        w32.Add(w33);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w35 = new Gtk.Label();
        w35.LabelProp = Mono.Unix.Catalog.GetString("Leave Fullscreen");
        w35.UseUnderline = true;
        w32.Add(w35);
        w31.Add(w32);
        this.btnExit.Add(w31);
        this.hbox2.Add(this.btnExit);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.hbox2[this.btnExit]));
        w39.Position = 6;
        w39.Expand = false;
        w39.Fill = false;
        w39.Padding = ((uint)(4));
        this.table2.Add(this.hbox2);
        Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table2[this.hbox2]));
        w40.RightAttach = ((uint)(2));
        w40.XOptions = ((Gtk.AttachOptions)(4));
        w40.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table2.Gtk.Table+TableChild
        this.ssPreviewArea = new Gtk.DrawingArea();
        this.ssPreviewArea.Name = "ssPreviewArea";
        this.table2.Add(this.ssPreviewArea);
        Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table2[this.ssPreviewArea]));
        w41.TopAttach = ((uint)(1));
        w41.BottomAttach = ((uint)(2));
        w41.RightAttach = ((uint)(2));
        this.Add(this.table2);
        if((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 839;
        this.DefaultHeight = 512;
        this.Show();
    }
}
