
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private Gtk.Table mainTable;
	private Gtk.HButtonBox btnsMainButtons;
	private Gtk.Button btnHelp;
	private Gtk.Button btnPowerManagement;
	private Gtk.Button btnClose;
	private Gtk.CheckButton chkActivateSS;
	private Gtk.CheckButton chkLockScreen;
	private Gtk.HBox hbModeControls;
	private Gtk.Label label2;
	private Gtk.ComboBox cmbMode;
	private Gtk.HBox hbRandomControls;
	private Gtk.Label label1;
	private Gtk.Label lblSpacer1;
	private Gtk.HScale hsCycleDelay;
	private Gtk.HButtonBox hbSelectionOptions;
	private Gtk.Button btnSelAll;
	private Gtk.Button btnSelNone;
	private Gtk.Button btnSelInv;
	private Gtk.HButtonBox hbSSButtons;
	private Gtk.Button btnSettings;
	private Gtk.Button btnFullscreen;
	private Gtk.HPaned hpCycleDelay;
	private Gtk.Fixed fixed5;
	private Gtk.Label lblCycleDelayValue;
	private Gtk.HScale hsIdleDelay;
	private Gtk.Label lblIdleDelayValue;
	private Gtk.DrawingArea ssPreviewArea;
	private Gtk.ScrolledWindow swScreensavers;
	private Gtk.TreeView tvScreenSavers;
	
	protected virtual void Build ()
	{
        Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = Mono.Unix.Catalog.GetString ("Screensaver Settings");
		this.Icon = Gdk.Pixbuf.LoadFromResource ("screensaversettings.icon.png");
		this.WindowPosition = ((Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainTable = new Gtk.Table (((uint)(9)), ((uint)(2)), false);
		this.mainTable.Name = "mainTable";
		this.mainTable.RowSpacing = ((uint)(6));
		this.mainTable.ColumnSpacing = ((uint)(6));
		// Container child mainTable.Gtk.Table+TableChild
		this.btnsMainButtons = new Gtk.HButtonBox ();
		this.btnsMainButtons.Name = "btnsMainButtons";
		this.btnsMainButtons.Spacing = 6;
		this.btnsMainButtons.LayoutStyle = ((Gtk.ButtonBoxStyle)(2));
		// Container child btnsMainButtons.Gtk.ButtonBox+ButtonBoxChild
		this.btnHelp = new Gtk.Button ();
		this.btnHelp.CanFocus = true;
		this.btnHelp.Name = "btnHelp";
		this.btnHelp.UseStock = true;
		this.btnHelp.UseUnderline = true;
		this.btnHelp.Label = "gtk-help";
		this.btnsMainButtons.Add (this.btnHelp);
        Gtk.ButtonBox.ButtonBoxChild w1 = ((Gtk.ButtonBox.ButtonBoxChild)(this.btnsMainButtons [this.btnHelp]));
		w1.Expand = false;
		w1.Fill = false;
		// Container child btnsMainButtons.Gtk.ButtonBox+ButtonBoxChild
		this.btnPowerManagement = new Gtk.Button ();
		this.btnPowerManagement.CanFocus = true;
		this.btnPowerManagement.Name = "btnPowerManagement";
		this.btnPowerManagement.UseUnderline = true;
        // Container child btnPowerManagement.Gtk.Container+ContainerChild
        Gtk.Alignment w2 = new Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w3 = new Gtk.HBox ();
		w3.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w4 = new Gtk.Image ();
		w4.Pixbuf = Stetic.IconLoader.LoadIcon (this, "gnome-power-manager", Gtk.IconSize.Menu);
		w3.Add (w4);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w6 = new Gtk.Label ();
		w6.LabelProp = Mono.Unix.Catalog.GetString ("Power Management");
		w6.UseUnderline = true;
		w3.Add (w6);
		w2.Add (w3);
		this.btnPowerManagement.Add (w2);
		this.btnsMainButtons.Add (this.btnPowerManagement);
        Gtk.ButtonBox.ButtonBoxChild w10 = ((Gtk.ButtonBox.ButtonBoxChild)(this.btnsMainButtons [this.btnPowerManagement]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child btnsMainButtons.Gtk.ButtonBox+ButtonBoxChild
		this.btnClose = new Gtk.Button ();
		this.btnClose.CanFocus = true;
		this.btnClose.Name = "btnClose";
		this.btnClose.UseStock = true;
		this.btnClose.UseUnderline = true;
		this.btnClose.Label = "gtk-close";
		this.btnsMainButtons.Add (this.btnClose);
        Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(this.btnsMainButtons [this.btnClose]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.mainTable.Add (this.btnsMainButtons);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.mainTable [this.btnsMainButtons]));
		w12.TopAttach = ((uint)(8));
		w12.BottomAttach = ((uint)(9));
		w12.RightAttach = ((uint)(2));
		w12.YPadding = ((uint)(4));
		w12.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.chkActivateSS = new Gtk.CheckButton ();
		this.chkActivateSS.CanFocus = true;
		this.chkActivateSS.Name = "chkActivateSS";
		this.chkActivateSS.Label = Mono.Unix.Catalog.GetString ("Regard the computer as idle after:");
		this.chkActivateSS.Active = true;
		this.chkActivateSS.DrawIndicator = true;
		this.chkActivateSS.UseUnderline = true;
		this.mainTable.Add (this.chkActivateSS);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.mainTable [this.chkActivateSS]));
		w13.TopAttach = ((uint)(6));
		w13.BottomAttach = ((uint)(7));
		w13.XOptions = ((Gtk.AttachOptions)(4));
		w13.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.chkLockScreen = new Gtk.CheckButton ();
		this.chkLockScreen.CanFocus = true;
		this.chkLockScreen.Name = "chkLockScreen";
		this.chkLockScreen.Label = Mono.Unix.Catalog.GetString ("Lock screen when screensaver is active");
		this.chkLockScreen.Active = true;
		this.chkLockScreen.DrawIndicator = true;
		this.chkLockScreen.UseUnderline = true;
		this.mainTable.Add (this.chkLockScreen);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.mainTable [this.chkLockScreen]));
		w14.TopAttach = ((uint)(7));
		w14.BottomAttach = ((uint)(8));
		w14.XOptions = ((Gtk.AttachOptions)(4));
		w14.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.hbModeControls = new Gtk.HBox ();
		this.hbModeControls.Name = "hbModeControls";
		this.hbModeControls.Spacing = 6;
		// Container child hbModeControls.Gtk.Box+BoxChild
		this.label2 = new Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = Mono.Unix.Catalog.GetString ("Show:");
		this.hbModeControls.Add (this.label2);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbModeControls [this.label2]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbModeControls.Gtk.Box+BoxChild
		this.cmbMode = Gtk.ComboBox.NewText ();
		this.cmbMode.AppendText (Mono.Unix.Catalog.GetString ("Blank Screen"));
		this.cmbMode.AppendText (Mono.Unix.Catalog.GetString ("One Screensaver"));
		this.cmbMode.AppendText (Mono.Unix.Catalog.GetString ("Randomly-chosen screensaver"));
		this.cmbMode.Name = "cmbMode";
		this.cmbMode.Active = 0;
		this.hbModeControls.Add (this.cmbMode);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbModeControls [this.cmbMode]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.mainTable.Add (this.hbModeControls);
        Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.mainTable [this.hbModeControls]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.YPadding = ((uint)(6));
		w17.XOptions = ((Gtk.AttachOptions)(4));
		w17.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.hbRandomControls = new Gtk.HBox ();
		this.hbRandomControls.Name = "hbRandomControls";
		this.hbRandomControls.Spacing = 6;
		// Container child hbRandomControls.Gtk.Box+BoxChild
		this.label1 = new Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = Mono.Unix.Catalog.GetString ("Cycle Delay:");
		this.label1.SingleLineMode = true;
		this.hbRandomControls.Add (this.label1);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbRandomControls [this.label1]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		w18.Padding = ((uint)(8));
		// Container child hbRandomControls.Gtk.Box+BoxChild
		this.lblSpacer1 = new Gtk.Label ();
		this.lblSpacer1.Name = "lblSpacer1";
		this.hbRandomControls.Add (this.lblSpacer1);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbRandomControls [this.lblSpacer1]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		w19.Padding = ((uint)(10));
		// Container child hbRandomControls.Gtk.Box+BoxChild
		this.hsCycleDelay = new Gtk.HScale (null);
		this.hsCycleDelay.CanFocus = true;
		this.hsCycleDelay.Name = "hsCycleDelay";
		this.hsCycleDelay.Adjustment.Upper = 100;
		this.hsCycleDelay.Adjustment.PageIncrement = 10;
		this.hsCycleDelay.Adjustment.StepIncrement = 1;
		this.hsCycleDelay.DrawValue = false;
		this.hsCycleDelay.Digits = 0;
		this.hsCycleDelay.ValuePos = ((Gtk.PositionType)(0));
		this.hbRandomControls.Add (this.hsCycleDelay);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbRandomControls [this.hsCycleDelay]));
		w20.Position = 2;
		this.mainTable.Add (this.hbRandomControls);
        Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.mainTable [this.hbRandomControls]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((Gtk.AttachOptions)(4));
		w21.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.hbSelectionOptions = new Gtk.HButtonBox ();
		this.hbSelectionOptions.Name = "hbSelectionOptions";
		// Container child hbSelectionOptions.Gtk.ButtonBox+ButtonBoxChild
		this.btnSelAll = new Gtk.Button ();
		this.btnSelAll.CanFocus = true;
		this.btnSelAll.Name = "btnSelAll";
		this.btnSelAll.UseUnderline = true;
		this.btnSelAll.Label = Mono.Unix.Catalog.GetString ("All");
		this.hbSelectionOptions.Add (this.btnSelAll);
        Gtk.ButtonBox.ButtonBoxChild w22 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbSelectionOptions [this.btnSelAll]));
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbSelectionOptions.Gtk.ButtonBox+ButtonBoxChild
		this.btnSelNone = new Gtk.Button ();
		this.btnSelNone.CanFocus = true;
		this.btnSelNone.Name = "btnSelNone";
		this.btnSelNone.UseUnderline = true;
		this.btnSelNone.Label = Mono.Unix.Catalog.GetString ("None");
		this.hbSelectionOptions.Add (this.btnSelNone);
        Gtk.ButtonBox.ButtonBoxChild w23 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbSelectionOptions [this.btnSelNone]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbSelectionOptions.Gtk.ButtonBox+ButtonBoxChild
		this.btnSelInv = new Gtk.Button ();
		this.btnSelInv.CanFocus = true;
		this.btnSelInv.Name = "btnSelInv";
		this.btnSelInv.UseUnderline = true;
		this.btnSelInv.Label = Mono.Unix.Catalog.GetString ("Invert");
		this.hbSelectionOptions.Add (this.btnSelInv);
        Gtk.ButtonBox.ButtonBoxChild w24 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbSelectionOptions [this.btnSelInv]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.mainTable.Add (this.hbSelectionOptions);
        Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.mainTable [this.hbSelectionOptions]));
		w25.TopAttach = ((uint)(3));
		w25.BottomAttach = ((uint)(4));
		w25.XOptions = ((Gtk.AttachOptions)(4));
		w25.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.hbSSButtons = new Gtk.HButtonBox ();
		this.hbSSButtons.Name = "hbSSButtons";
		this.hbSSButtons.Spacing = 6;
		// Container child hbSSButtons.Gtk.ButtonBox+ButtonBoxChild
		this.btnSettings = new Gtk.Button ();
		this.btnSettings.CanFocus = true;
		this.btnSettings.Name = "btnSettings";
		this.btnSettings.UseUnderline = true;
        // Container child btnSettings.Gtk.Container+ContainerChild
        Gtk.Alignment w26 = new Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w27 = new Gtk.HBox ();
		w27.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w28 = new Gtk.Image ();
		w28.Pixbuf = Stetic.IconLoader.LoadIcon (this, "gtk-properties", Gtk.IconSize.Menu);
		w27.Add (w28);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w30 = new Gtk.Label ();
		w30.LabelProp = Mono.Unix.Catalog.GetString ("_Options");
		w30.UseUnderline = true;
		w27.Add (w30);
		w26.Add (w27);
		this.btnSettings.Add (w26);
		this.hbSSButtons.Add (this.btnSettings);
        Gtk.ButtonBox.ButtonBoxChild w34 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbSSButtons [this.btnSettings]));
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbSSButtons.Gtk.ButtonBox+ButtonBoxChild
		this.btnFullscreen = new Gtk.Button ();
		this.btnFullscreen.CanFocus = true;
		this.btnFullscreen.Name = "btnFullscreen";
		this.btnFullscreen.UseUnderline = true;
        // Container child btnFullscreen.Gtk.Container+ContainerChild
        Gtk.Alignment w35 = new Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w36 = new Gtk.HBox ();
		w36.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w37 = new Gtk.Image ();
		w37.Pixbuf = Stetic.IconLoader.LoadIcon (this, "gtk-fullscreen", Gtk.IconSize.Menu);
		w36.Add (w37);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w39 = new Gtk.Label ();
		w39.LabelProp = Mono.Unix.Catalog.GetString ("_Test");
		w39.UseUnderline = true;
		w36.Add (w39);
		w35.Add (w36);
		this.btnFullscreen.Add (w35);
		this.hbSSButtons.Add (this.btnFullscreen);
        Gtk.ButtonBox.ButtonBoxChild w43 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbSSButtons [this.btnFullscreen]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		this.mainTable.Add (this.hbSSButtons);
        Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.mainTable [this.hbSSButtons]));
		w44.TopAttach = ((uint)(4));
		w44.BottomAttach = ((uint)(5));
		w44.XOptions = ((Gtk.AttachOptions)(4));
		w44.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.hpCycleDelay = new Gtk.HPaned ();
		this.hpCycleDelay.CanFocus = true;
		this.hpCycleDelay.Name = "hpCycleDelay";
		this.hpCycleDelay.Position = 120;
		// Container child hpCycleDelay.Gtk.Paned+PanedChild
		this.fixed5 = new Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hpCycleDelay.Add (this.fixed5);
        Gtk.Paned.PanedChild w45 = ((Gtk.Paned.PanedChild)(this.hpCycleDelay [this.fixed5]));
		w45.Resize = false;
		// Container child hpCycleDelay.Gtk.Paned+PanedChild
		this.lblCycleDelayValue = new Gtk.Label ();
		this.lblCycleDelayValue.Name = "lblCycleDelayValue";
		this.lblCycleDelayValue.Xalign = 0F;
		this.lblCycleDelayValue.LabelProp = Mono.Unix.Catalog.GetString ("1 minute");
		this.hpCycleDelay.Add (this.lblCycleDelayValue);
		this.mainTable.Add (this.hpCycleDelay);
        Gtk.Table.TableChild w47 = ((Gtk.Table.TableChild)(this.mainTable [this.hpCycleDelay]));
		w47.LeftAttach = ((uint)(1));
		w47.RightAttach = ((uint)(2));
		w47.XOptions = ((Gtk.AttachOptions)(4));
		w47.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.hsIdleDelay = new Gtk.HScale (null);
		this.hsIdleDelay.CanFocus = true;
		this.hsIdleDelay.Name = "hsIdleDelay";
		this.hsIdleDelay.Adjustment.Lower = 1;
		this.hsIdleDelay.Adjustment.Upper = 120;
		this.hsIdleDelay.Adjustment.PageIncrement = 10;
		this.hsIdleDelay.Adjustment.StepIncrement = 1;
		this.hsIdleDelay.DrawValue = false;
		this.hsIdleDelay.Digits = 0;
		this.hsIdleDelay.ValuePos = ((Gtk.PositionType)(2));
		this.mainTable.Add (this.hsIdleDelay);
        Gtk.Table.TableChild w48 = ((Gtk.Table.TableChild)(this.mainTable [this.hsIdleDelay]));
		w48.TopAttach = ((uint)(6));
		w48.BottomAttach = ((uint)(7));
		w48.LeftAttach = ((uint)(1));
		w48.RightAttach = ((uint)(2));
		w48.XOptions = ((Gtk.AttachOptions)(4));
		w48.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.lblIdleDelayValue = new Gtk.Label ();
		this.lblIdleDelayValue.Name = "lblIdleDelayValue";
		this.lblIdleDelayValue.Xalign = 0F;
		this.lblIdleDelayValue.LabelProp = Mono.Unix.Catalog.GetString ("1 minute");
		this.lblIdleDelayValue.SingleLineMode = true;
		this.mainTable.Add (this.lblIdleDelayValue);
        Gtk.Table.TableChild w49 = ((Gtk.Table.TableChild)(this.mainTable [this.lblIdleDelayValue]));
		w49.TopAttach = ((uint)(5));
		w49.BottomAttach = ((uint)(6));
		w49.LeftAttach = ((uint)(1));
		w49.RightAttach = ((uint)(2));
		w49.XOptions = ((Gtk.AttachOptions)(4));
		w49.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.ssPreviewArea = new Gtk.DrawingArea ();
		this.ssPreviewArea.Name = "ssPreviewArea";
		this.mainTable.Add (this.ssPreviewArea);
        Gtk.Table.TableChild w50 = ((Gtk.Table.TableChild)(this.mainTable [this.ssPreviewArea]));
		w50.TopAttach = ((uint)(2));
		w50.BottomAttach = ((uint)(5));
		w50.LeftAttach = ((uint)(1));
		w50.RightAttach = ((uint)(2));
		w50.XPadding = ((uint)(4));
		w50.YPadding = ((uint)(2));
		w50.YOptions = ((Gtk.AttachOptions)(4));
		// Container child mainTable.Gtk.Table+TableChild
		this.swScreensavers = new Gtk.ScrolledWindow ();
		this.swScreensavers.CanFocus = true;
		this.swScreensavers.Name = "swScreensavers";
		this.swScreensavers.HscrollbarPolicy = ((Gtk.PolicyType)(2));
		this.swScreensavers.ShadowType = ((Gtk.ShadowType)(1));
		// Container child swScreensavers.Gtk.Container+ContainerChild
		this.tvScreenSavers = new Gtk.TreeView ();
		this.tvScreenSavers.CanFocus = true;
		this.tvScreenSavers.Name = "tvScreenSavers";
		this.tvScreenSavers.HeadersVisible = false;
		this.swScreensavers.Add (this.tvScreenSavers);
		this.mainTable.Add (this.swScreensavers);
        Gtk.Table.TableChild w52 = ((Gtk.Table.TableChild)(this.mainTable [this.swScreensavers]));
		w52.TopAttach = ((uint)(2));
		w52.BottomAttach = ((uint)(3));
		w52.XPadding = ((uint)(4));
		w52.XOptions = ((Gtk.AttachOptions)(4));
		this.Add (this.mainTable);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 863;
		this.DefaultHeight = 656;
		this.Show ();
	}
}
