
// This file has been generated by the GUI designer. Do not modify.

public partial class SettingsUI
{
	protected virtual void Build ()
	{
        Stetic.Gui.Initialize (this);
		// Widget SettingsUI
		this.Name = "SettingsUI";
		this.Title = Mono.Unix.Catalog.GetString ("SettingsUI");
		this.Icon = Gdk.Pixbuf.LoadFromResource ("screensaversettings.icon.png");
		this.WindowPosition = ((Gtk.WindowPosition)(4));
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 375;
		this.DefaultHeight = 300;
		this.Show ();
	}
}
